In [1]:
mystring = 'all lowercase'

In [2]:
mynewstring = 'A' + mystring[1:]

In [3]:
mynewstring

'All lowercase'

## Lists

* Can take any type of data types

In [4]:
my_list = [23, True, 'Cheese', 3.1249]

In [5]:
my_list[1] # Indexing the list

True

In [6]:
my_list[0] = 35 # To replace a value in the list

In [7]:
my_list

[35, True, 'Cheese', 3.1249]

In [8]:
my_list.append('45') # Adding the elements to the list with the append function

In [9]:
my_list

[35, True, 'Cheese', 3.1249, '45']

In [10]:
my_list[5] = 'Hey there brown cow' # This does not work in terms of list

IndexError: list assignment index out of range

In [11]:
for i in my_list:
    print (type(i))

<class 'int'>
<class 'bool'>
<class 'str'>
<class 'float'>
<class 'str'>


## Aliases and Clones

### Aliases

In [12]:
a = [5, 10, 50, 100]

In [13]:
b=a

In [14]:
b

[5, 10, 50, 100]

In [15]:
a[0] = 'Changed'

In [16]:
b # Even b[0] changed, when we changed a[0]

['Changed', 10, 50, 100]

### Clones

* when we use the slice method, we can observe that even though we changed the value of a[0], b[0] did not change

In [20]:
a = [5, 10, 50, 100]

In [21]:
b = a[:]

In [22]:
a[0] = 'Changed'

In [23]:
b

[5, 10, 50, 100]

In [24]:
a

['Changed', 10, 50, 100]

## Sets

* Sets only contain unique values
* Set containing only one value is called as a Singleton
* Since Sets are unordered, we cannot perform indexing

In [26]:
aset = {11,22,33}

In [27]:
bset = aset

In [28]:
aset = aset | {55}

In [29]:
aset

{11, 22, 33, 55}

In [31]:
bset # The other set will not be updated, even though it is an alias

{11, 22, 33}

In [33]:
alist = [11,22,33,22,44]

In [36]:
aset = set(alist) # Converting a list to a set

In [35]:
aset

{11, 22, 33, 44}

In [38]:
aset = aset + {55} # We cannot perform a addition type in sets, but we can add with "|"(pipe) symbol

TypeError: unsupported operand type(s) for +: 'set' and 'set'

In [39]:
aset = {11,22,33}
bset = {12,23,33}

In [40]:
aset | bset # Union of two sets

{11, 12, 22, 23, 33}

In [41]:
aset & bset # Intersection of two sets

{33}

In [42]:
aset - bset # Difference between two sets

{11, 22}

In [43]:
aset ^ bset # Symmetric difference between two sets (AUB) - (AnB)

{11, 12, 22, 23}

## Numpy

* Fullform of Numpy is numeric python

In [45]:
import numpy as np # Importing the numpy package

In [49]:
list_1 = [[1,2,3,4], [5,6,7,8]]
list_1

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [48]:
array_1 = np.array(list_1) # To convert a list to an array
array_1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
array_1.__class__ # To check the class of an object

numpy.ndarray

In [56]:
array_1.ndim # number of dimensions in the array

2

In [54]:
array_1.shape # Shape of the array

(2, 4)

In [58]:
type(array_1) # type function can also be used

numpy.ndarray

In [59]:
np.zeros((3,5)) # Creating an array entirely with zeroes with desired shape

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [61]:
np.arange(20).reshape(4,5) # reshape function is used to reshape an array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])